### ISSUE TITLE
Unable to converse with gpt model through  Azure OpenAI Chat Assistant

### ISSUE THREAD

**Issue by gujju62** [Azure-Samples/azureai-assistant-tool#47] opened 2024-09-24 13:15 UTC
> Please provide us with the following information:
While trying to chat with Azure Open AI gpt-4 model as service using the chat assistant feature, I am getting error message "Failed to create thread Error Code 404.  I have done following :
 - Have followed the installation guidelines
 -  Have validated the access to gpt-4 service endpoint using nslookup
 -  Tried to access the services using the  URL provided by Azure OpenAI  from Postman and I am getting response.
 - Have used deployment names  in "Settings" -->  system assistant and while creating new chat assistant 
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
 - Create  New Chat Assistant
 - Start the conversation 

### Any log messages given by the failure
>
![image](https://github.com/user-attachments/assets/78488738-609d-44ba-b759-fe6977970640)

![image](https://github.com/user-attachments/assets/47350108-3f94-4837-82f0-6e4edbc3ba0a)

![image](https://github.com/user-attachments/assets/78673b61-b196-433e-8c11-2510952278d8)

### Expected/desired behavior
>
Should be able to have the chat conversation 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Linux ubuntu 20.04

### Versions
>
0.4.5 version for the Assistant

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jhakulin** [comment] 2024-09-24 15:19
@gujju62 Thanks for the report. In the first error message, I see "Resource not found", thus I wonder if the endpoint or the model deployment name is set correctly for assistant."

Did you have following format in AZURE_OPENAI_ENDPOINT=<your endpoint data>.openai.azure.com/?
Then did you use the model deployment name from Azure AI Studio, ie, not the model name (as that may be different).

**Comment by gujju62** [comment] 2024-09-24 15:44
@jhakulin  - Thank you . 
Yes, I am using the endpoints and key provided by Azure OpenAI service.

I am  also using using the deployment name that i have  provided while creating the service.

cheers.

**Comment by jhakulin** [comment] 2024-09-24 16:00
@gujju62 Need to figure out what is wrong as I cannot reproduce.

Could you please enable OpenAI logging check box in Debug view and send new trace to me to jhakulin@microsoft.com?
NOTE: When you enable the OpenAI logging your api-key seems get exposed, so be careful and remove that before sharing the information.
![image](https://github.com/user-attachments/assets/bb0ce760-9675-4e40-bcfe-d7b232b2c8eb)

Also could you do `pip list` for the components you have installed.

**Comment by gujju62** [comment] 2024-09-25 09:27
@jhakulin - Please find attached the list of packages installed [pip install].  Under Menu Item "Diagnostics --> Debug View", I don't see any option for enabling OpenAI logging.
[packageslist.txt](https://github.com/user-attachments/files/17128613/packageslist.txt)

**Comment by jhakulin** [comment] 2024-09-25 14:08
@gujju62 You do not see check box like below?
![image](https://github.com/user-attachments/assets/4512e068-46f5-425a-be04-896e7ffacf9a)

**Comment by gujju62** [comment] 2024-09-25 17:17
@jhakulin - I have emailed you sample trace .
Thanks.

**Comment by jhakulin** [comment] 2024-09-26 01:35
@gujju62 One problem could be that you have 2023-03-15-preview api version.

For assistants, please use

set AZURE_OPENAI_API_VERSION=2024-05-01-preview

**Comment by gujju62** [comment] 2024-09-26 15:08
@jhakulin - With the API version change, I was able to access the tool and able to perform chat with the assistant. Thank you for your help. 

I am also trying out speech capability of the tool, is there any documentation that you could point to me?

Thank you.

**Comment by jhakulin** [comment] 2024-09-26 15:52
@gujju62 Great, please see instructions here how to get Azure Speech resource

https://learn.microsoft.com/en-us/azure/ai-services/speech-service/get-started-speech-to-text?tabs=linux%2Cterminal&pivots=programming-language-python

Once you get key and region, please update environment variables

set AZURE_AI_SPEECH_KEY=Your_Speech_Key
set AZURE_AI_SPEECH_REGION=Your_Speech_Region

The same resource should work for both speech to text and text to speech

**Comment by jhakulin** [comment] 2024-09-27 02:21
closing the issue, please let me know if need more help.

**Closed by jhakulin** 2024-09-27 02:21 UTC
